version: '3.1'
volumes:
  pg_timeweb:
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=megatest
      - POSTGRES_USER=megatest
      - POSTGRES_DB=megatest
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432